### ISSUE TITLE
TypeError: expected a character buffer object

### ISSUE THREAD

**Issue by gunnardag** [sindrig/spoppy#102]
Using Python 2.7.10
When loggin in initially I got a TypeError: expected a character buffer object

Stacktrace:
Traceback (most recent call last):
  File "./.local/bin/spoppy", line 11, in <module>
    main()
  File "/home/gunnar/.local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/gunnar/.local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/gunnar/.local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/gunnar/.local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/gunnar/.local/lib/python2.7/site-packages/spoppy/__init__.py", line 42, in main
    username, password = get_config_from_user()
  File "/home/gunnar/.local/lib/python2.7/site-packages/spoppy/config.py", line 32, in get_config_from_user
    set_config(username, password)
  File "/home/gunnar/.local/lib/python2.7/site-packages/spoppy/config.py", line 22, in set_config
    f.write(username)
TypeError: expected a character buffer object

**Comment by sindrig** [comment]
@gunnardag you can update to v1.4.4 using `pip install spoppy --upgrade`
