### ISSUE TITLE
Error when trying to shuffle play empty playlist

### ISSUE THREAD

**Issue by sindrig** [sindrig/spoppy#8]
If you have an empty playlist and try to shuffle play it, the program crashes.

**Comment by sindrig** [comment]
Traceback (most recent call last):
  File "spoppy.py", line 42, in <module>
    main(auto_envvar_prefix='SPOPPY', standalone_mode=False)
  File "/home/sindri/dev/spoppy/lib/python3.5/site-packages/click/core.py", line 717, in __call__
    return self.main(*args, **kwargs)
  File "/home/sindri/dev/spoppy/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/sindri/dev/spoppy/lib/python3.5/site-packages/click/core.py", line 890, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sindri/dev/spoppy/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "spoppy.py", line 35, in main
    navigator.start()
  File "/home/sindri/dev/spoppy/spoppy/spoppy/navigation.py", line 34, in start
    self.navigate_to(main_menu)
  File "/home/sindri/dev/spoppy/spoppy/spoppy/navigation.py", line 71, in navigate_to
    self.navigate_to(response)
  File "/home/sindri/dev/spoppy/spoppy/spoppy/navigation.py", line 71, in navigate_to
    self.navigate_to(response)
  File "/home/sindri/dev/spoppy/spoppy/spoppy/navigation.py", line 70, in navigate_to
    response = response()
  File "/home/sindri/dev/spoppy/spoppy/spoppy/menus.py", line 187, in shuffle_play
    self.navigator.player.play_current_song()
  File "/home/sindri/dev/spoppy/spoppy/spoppy/players.py", line 201, in play_current_song
    current_track = self.get_track_by_idx(self.current_track_idx)
  File "/home/sindri/dev/spoppy/spoppy/spoppy/players.py", line 163, in get_track_by_idx
    song_index = self.song_order[idx]
IndexError: list index out of range
