### ISSUE TITLE
Artist name can be None?

### ISSUE THREAD

**Issue by sindrig** [sindrig/spoppy#9]
Traceback (most recent call last):
  File "spoppy.py", line 44, in <module>
    main(auto_envvar_prefix='SPOPPY')
  File "/home/sindri/dev/spoppy/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/sindri/dev/spoppy/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/sindri/dev/spoppy/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sindri/dev/spoppy/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "spoppy.py", line 35, in main
    navigator.start()
  File "/home/sindri/dev/spoppy/spoppy/spoppy/navigation.py", line 34, in start
    self.navigate_to(main_menu)
  File "/home/sindri/dev/spoppy/spoppy/spoppy/navigation.py", line 72, in navigate_to
    self.navigate_to(response)
  File "/home/sindri/dev/spoppy/spoppy/spoppy/navigation.py", line 72, in navigate_to
    self.navigate_to(response)
  File "/home/sindri/dev/spoppy/spoppy/spoppy/navigation.py", line 50, in navigate_to
    going.initialize()
  File "/home/sindri/dev/spoppy/spoppy/spoppy/menus.py", line 84, in initialize
    self._options = Options(self.get_options())
  File "/home/sindri/dev/spoppy/spoppy/spoppy/menus.py", line 209, in get_options
    format_track(track), self.select_song(i)
  File "/home/sindri/dev/spoppy/spoppy/spoppy/util.py", line 48, in format_track
    artist.name for artist in track.artists
TypeError: sequence item 0: expected str instance, NoneType found

**Comment by sindrig** [comment]
This introduced a new issue https://github.com/sindrig/spoppy/issues/12
